[project]
name = "ds-container-workspace"
version = "0.1.0"
requires-python = ">=3.10"
license = { file = "LICENSE" }

dependencies = [
    "numpy==2.2.4",
    "pandas==2.2.3",
    "matplotlib==3.10.1",
    "seaborn==0.13.2",
    "scikit-learn==1.6.1",
    "jupyterlab==4.4.0",
]

[tool.hatch.build.targets.wheel]
packages = ["tools"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
